baseurl: "/iOS-shortcuts"
url: "https://edbritton.github.io"
repository: edbritton/iOS-shortcuts
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
aux_links:
  "View on GitHub":
    - "https://github.com/edbritton/iOS-shortcuts"
  "My Projects":
    - "/repos"
  "My Website":
    - "/"
search_enabled: false
markdown: GFM
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-readme-index
  - jekyll-titles-from-headings