title: Ed’s iOS Shortcuts
remote_theme: edbritton/edbritton.github.io
sass:
  style: compressed # possible values: nested expanded compact compressed
markdown: GFM
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-redirect-from
  - jekyll-seo-tag
